common:
  encrypt:
    password: ${ENCRYPTION_PASSWORD:openblocks.dev}
    salt: ${ENCRYPTION_SALT:openblocks.dev}
  security:
    cors-allowed-domains: ${CORS_ALLOWED_DOMAINS:*}
  max-query-request-size-in-mb: 20
  max-query-response-size-in-mb: 20

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/openblocks?socketTimeoutMS=5000}
  redis:
    url: ${REDIS_URL:redis://localhost:6379}