common:
  encrypt:
    password: ${ENCRYPTION_PASSWORD:openblocks.dev}
    salt: ${ENCRYPTION_SALT:openblocks.dev}
  security:
    corsAllowedDomainString: ${CORS_ALLOWED_DOMAINS:*}
  workspace:
    mode: ENTERPRISE

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/openblocks?socketTimeoutMS=5000}
  redis:
    url: ${REDIS_URL:redis://localhost:6379}